name: deploy-preprod

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: "16.x"
    - uses: actions/setup-ruby@v1
    - run: gem install compass
    - run: yarn --frozen-lockfile
    - run: yarn test
    - run: yarn grunt deploy-preprod
